### ISSUE TITLE
Bugs ? on self.send_dm_webapi

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#166]
Hello 
here a piece of code for one of my plugin 

`    @schedule(hour='22', minute='49')
    def humeurJour(self):
        """humeurJour : demande l'humeur du jour sur le canal meteo"""
        for u in session.query(users).order_by(users.id):
            print(u.name)
            self.send_dm_webapi(u.userID,
                                'Salut , ' + u.name +
                                ' ,comment ça va aujourdhui')`
, when it runs , i have this in logs files
`Traceback (most recent call last):
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/projets/supportBot/mybot/plugins/meteo.py", line 22, in humeurJour
    ' ,comment ça va aujourdhui')
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/plugins/base.py", line 223, in send_dm_webapi
    return self._client.send_dm_webapi(user, text, attachments)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/slack.py", line 93, in send_dm_webapi
    dm_channel = self.open_im(u.id)
  File "/home/pi/projets/supportBot/lib/python3.5/site-packages/machine/slack.py", line 78, in open_im
    return response['channel']['id']
KeyError: 'channel'`

**Comment by dorel14** [comment]
Idem 
auto solve icoming from my test slack instance not having all users of prod.
I close
