### ISSUE TITLE
Error on querying slack api

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#228]
Hello 
I've launch my slack machine in real prodcution and i have this error message when trying to load users informations

`Traceback (most recent call last):
  File "/home/supportbot/bot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/core.py", line 219, in run
    self._dispatcher.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/dispatch.py", line 29, in start
    for event in self._client.rtm_read():
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/server.py", line 296, in websocket_safe_read
    "Unable to send due to closed RTM websocket"
slackclient.server.SlackConnectionError: Unable to send due to closed RTM websocket`

**Comment by dorel14** [comment]
Same as  #54
