### ISSUE TITLE
Bug on send_dm

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#276]
hello
On send_dm , i'have this error
'Traceback (most recent call last):
  File "/home/devsupportbot/bot/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/devsupportbot/bot/mybot/plugins/meteo.py", line 38, in humeurJour
    Réagis en cliquant sur une icône''')
  File "/home/devsupportbot/bot/lib/python3.6/site-packages/machine/plugins/base.py", line 191, in send_dm
    self._client.send_dm(user, text)
  File "/home/devsupportbot/bot/lib/python3.6/site-packages/machine/slack.py", line 82, in send_dm
    dm_channel = self.open_im(u.id)
AttributeError: 'NoneType' object has no attribute 'id''

here is my code
`  def humeurJour(self):
        """humeurJour : demande l'humeur du jour sur le canal meteo"""
        for u in DbSession.query(users.utilisateur,
                                 slackusers.name,
                                 slackusers.user_id).join(slackusers,
                                                          services).filter(
                services.nom == "Support").order_by(
                users.slackid):
            print(u.utilisateur, u.name, u.user_id)
            msg = self.send_dm(u.name,
                               'Salut , ' + u.name +
                               ''' ,comment vas tu aujourdhui? \n
                                      Réagis en cliquant sur une icône''')
            channel = msg['channel']
            reaction_channel.append(channel)
            ts = msg['ts']
            for i in DbSession.query(emojis).order_by(emojis.score):
                print(i.emoji)
                self.react(channel, ts, i.emoji)`

**Comment by dorel14** [comment]
auto solve icoming from my test slack instance not having all users of prod.
I close
