### ISSUE TITLE
error message on scheduler task

### ISSUE THREAD

**Issue by dorel14** [DandyDev/slack-machine#347]
Hello
I have a plugin that look at gmail message and send a notification to slack
```
from machine.plugins.base import MachineBasePlugin
from plugins.helpers.gmail import Gmail
from machine.plugins.decorators import schedule, listen_to


class schedmail(MachineBasePlugin):
    @schedule(day_of_week='mon-fri', hour='8-17', minute='00-59/5')
    def extranetbloquant(self):
        reponse = Gmail().readMailExtranet(['INBOX', 'bloquant'], ['bloquant'])
        if reponse:
            self.say('akuiteo-bloquant', reponse)
```
and i have regurlarly this message in logs
```
[2020-05-18 14:00:01][ERROR] apscheduler.executors.default base.py:run_job:131 | Job "schedmail.extranetbloquant (trigger: cron[day_of_week='mon-fri', hour='8-17', minute='0-59/5'], next run at: 2020-05-18 14:05:00 CEST)" raised an exception
Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/supportbot/bot/mybot/plugins/mailtoslack.py", line 12, in extranetbloquant
    self.say('akuiteo-bloquant', reponse)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/plugins/base.py", line 137, in say
    thread_ts=thread_ts, ephemeral_user=ephemeral_user, **kwargs)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/slack.py", line 61, in send
    **kwargs
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/web/client.py", line 559, in chat_postMessage
    return self.api_call("chat.postMessage", json=kwargs)
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/web/base_client.py", line 171, in api_call
    return self._event_loop.run_until_complete(future)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 455, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 409, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running


```
after some research with google , i found this
https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python
https://github.com/erdewit/nest_asyncio

**Comment by DandyDev** [comment]
There was an error in `slackclient` that was resolved with a new version. I will update the dependency on `slackclient` and publish a new version of Slack Machine this week,

**Comment by dorel14** [comment]
ok thx
will this update also correct this problem 
'''
127.0.0.1 - - [29/May/2020 10:06:02] "GET /DataTables-1.10.20/images/sort_asc.png HTTP/1.1" 304 0
[2020-05-29 11:18:08][ERROR] slack.rtm.client client.py:_dispatch_event:445 | When calling '#_on_user_change()' in the 'machine.clients.singletons.slack' module the following error was raised: missing value for field "deleted"
Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 47, in from_dict
    field_data = data[field.name]
KeyError: 'deleted'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 59, in from_dict
    value = get_default_value_for_field(field)
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/core.py", line 211, in run
    self._dispatcher.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/dispatch.py", line 34, in start
    self._client.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 118, in start
    self.rtm_client.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 198, in start
    return self._event_loop.run_until_complete(future)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 440, in _dispatch_event
    self._execute_in_thread(callback, data)
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 465, in _execute_in_thread
    future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 82, in _on_user_change
    user = self._register_user(payload['data']['user'])
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 44, in _register_user
    user = User.from_api_response(user_response)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/models/user.py", line 57, in from_api_response
    return from_dict(data_class=User, data=user_reponse)  # pragma: no cover
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 63, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "deleted"
Bottle v0.13-dev server starting up (using WSGIRefServer())...
'''

**Comment by dorel14** [comment]
And this one
~~~
[2020-05-29 11:22:26][ERROR] slack.rtm.client client.py:_dispatch_event:445 | When calling '#_on_user_change()' in the 'machine.clients.singletons.slack' module the following error was raised: missing value for field "deleted"
Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 47, in from_dict
    field_data = data[field.name]
KeyError: 'deleted'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 59, in from_dict
    value = get_default_value_for_field(field)
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/core.py", line 211, in run
    self._dispatcher.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/dispatch.py", line 34, in start
    self._client.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 118, in start
    self.rtm_client.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 198, in start
    return self._event_loop.run_until_complete(future)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 339, in _connect_and_read
    await self._read_messages()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 390, in _read_messages
    await self._dispatch_event(event, data=payload)
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 440, in _dispatch_event
    self._execute_in_thread(callback, data)
  File "/home/supportbot/bot/lib/python3.6/site-packages/slack/rtm/client.py", line 465, in _execute_in_thread
    future.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 82, in _on_user_change
    user = self._register_user(payload['data']['user'])
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 44, in _register_user
    user = User.from_api_response(user_response)
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/models/user.py", line 57, in from_api_response
    return from_dict(data_class=User, data=user_reponse)  # pragma: no cover
  File "/home/supportbot/bot/lib/python3.6/site-packages/dacite/core.py", line 63, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "deleted"
~~~

**Comment by repudi8or** [comment]
any update on this one? its tripping up my plugins using schedule

**Comment by dorel14** [comment]
HI , when do you think you can publish a new release ? i have some time to test next week

thx

**Comment by dorel14** [comment]
any update on this one? its tripping up my plugins using schedule

**Comment by repudi8or** [comment]
this now seems fixed on latest master

**Comment by DandyDev** [comment]
Hey @dorel14 and @repudi8or this is indeed fixed on master, but I forgot to cut a release. I was very busy with work but I'm now on holiday, so I will cut a release tomorrow.

**Comment by DandyDev** [comment]
You can upgrade to [v0.20](https://pypi.org/project/slack-machine/0.20.0/) to get the fixes
