### ISSUE TITLE
Failed to send a request to Slack API server: <urlopen error no host given>

### ISSUE THREAD

**Issue by repudi8or** [DandyDev/slack-machine#383]
On merging master here into my fork i am now getting the following.....  
i'm guessing its something in the handoff to the slack rtm client, currently looking at what may have changed there

> Successfully built slack-machine
Installing collected packages: slack-machine
Successfully installed slack-machine-0.19.2
(slack-machine) bash-3.2$ slack-machine
Initializing Slack Machine:
    Loading settings...
    Initializing storage using backend: machine.storage.backends.memory.MemoryStorage
    Loading plugins...
        ✓ machine.plugins.builtin.general:PingPongPlugin
        ✓ machine.plugins.builtin.general:HelloPlugin
        ✓ machine.plugins.builtin.help:HelpPlugin
        ✓ machine.plugins.builtin.fun.images:ImageSearchPlugin
        ✓ machine.plugins.builtin.fun.memes:MemePlugin
        ✓ machine.plugins.prinfo:PRInfoPlugin
Starting Slack Machine:
    ✓ Connected to Slack
    ✓ Scheduler started
Bottle v0.13-dev server starting up (using WSGIRefServer())...
Listening on http://0.0.0.0:8080/
Hit Ctrl-C to quit.
    ✓ Web server started
    ✓ Keepalive thread started [Interval: 5s]
    ✓ Dispatcher started
[2020-07-16 09:41:57][ERROR] slack.web.base_client base_client.py:_perform_urllib_http_request:582 | Failed to send a request to Slack API server: <urlopen error no host given>
Traceback (most recent call last):
  File "/private/tmp/slack-machine/.venv/bin/slack-machine", line 8, in <module>
    sys.exit(main())
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/machine/core.py", line 211, in run
    self._dispatcher.start()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/machine/dispatch.py", line 34, in start
    self._client.start()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/machine/clients/singletons/slack.py", line 118, in start
    self.rtm_client.start()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/rtm/client.py", line 206, in start
    return self._event_loop.run_until_complete(future)
  File "/Users/myuser/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/rtm/client.py", line 352, in _connect_and_read
    url, data = await self._retrieve_websocket_info()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/rtm/client.py", line 547, in _retrieve_websocket_info
    resp = self._web_client.rtm_connect()
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/client.py", line 1695, in rtm_connect
    return self.api_call("rtm.connect", http_verb="GET", params=kwargs)
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/base_client.py", line 215, in api_call
    return self._sync_send(api_url=api_url, req_args=req_args)
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/base_client.py", line 348, in _sync_send
    additional_headers=headers,
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/base_client.py", line 452, in _urllib_api_call
    response = self._perform_urllib_http_request(url=url, args=request_args)
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/base_client.py", line 583, in _perform_urllib_http_request
    raise err
  File "/private/tmp/slack-machine/.venv/lib/python3.6/site-packages/slack/web/base_client.py", line 564, in _perform_urllib_http_request
    req, context=self.ssl, timeout=self.timeout
  File "/Users/myuser/.pyenv/versions/3.6.9/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/myuser/.pyenv/versions/3.6.9/lib/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/Users/myuser/.pyenv/versions/3.6.9/lib/python3.6/urllib/request.py", line 1241, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
(slack-machine) bash-3.2$

**Comment by repudi8or** [comment]
Just a note here, this is related to http_proxy being set to '' rather than None on the call to rtm_client.... Im trying to work out why this is now happening, but a workaround is to add to local_settings.py :-
`HTTP_PROXY = None`

**Comment by DandyDev** [comment]
Thanks for the report and apologies with the late response. I will fix this tomorrow.

**Comment by DandyDev** [comment]
This is fixed in 07f2f60d4ff60a64ecc1c06c0443a8c8095b173a

**Comment by DandyDev** [comment]
You can upgrade to [v0.20](https://pypi.org/project/slack-machine/0.20.0/) to get the fixes
