### ISSUE TITLE
Connection is closing every few days

### ISSUE THREAD

**Issue by Tahvok** [DandyDev/slack-machine#54]
Every other day, slack bot is losing it's connection from some reason:
```
Traceback (most recent call last):
  File "/root/virtualenvs/tedbot/bin/slack-machine", line 11, in <module>
    sys.exit(main())
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/machine/core.py", line 198, in run
    self._dispatcher.start()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/machine/dispatch.py", line 23, in start
    for event in self._client.rtm_read():
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/slackclient/client.py", line 135, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/slackclient/server.py", line 194, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_core.py", line 300, in recv
    opcode, data = self.recv_data()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_core.py", line 317, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_core.py", line 330, in recv_data_frame
    frame = self.recv_frame()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_core.py", line 364, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_core.py", line 434, in _recv
    return recv(self.sock, bufsize)
  File "/root/virtualenvs/tedbot/lib/python3.5/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
```

Not sure what is going on, but can the slack bot try to reconnect to slack if that happens. Or perhaps there should be some other approach?

**Comment by DandyDev** [comment]
Thanks for reporting this! I think some reconnection logic is on order here. I will think about it a bit. In the meanwhile, as a workaround, as long as you use some persistent storage, you could restart Slack Machine yourself every day or so.

**Comment by Tahvok** [comment]
We have wrote this service to workaround the issue:
```
[Unit]
Description=slack-machine slack bot
After=multi-user.target

[Service]
Type=idle
Restart=always
WorkingDirectory=/root/tedbot
ExecStart=/root/virtualenvs/tedbot/bin/python3 /root/virtualenvs/tedbot/bin/slack-machine

[Install]
WantedBy=multi-user.target
```

**Comment by DandyDev** [comment]
Great! I have been running a bot for my team for the past 3 months, and I haven't had any disconnects happen. I'm running it inside Docker.

**Comment by preludedrew** [comment]
I was able to confirm this issue over the weekend. I was seeing disconnects at almost eactly 24 hours each time, but today the disconnect was at the 8hr mark. The bot is running idle mostly while I've been working on other projects, so I'm guessing there's some sort of idle disconnect on the RTM end. Although the RTM protocol doesn't say it's required, maybe adding a Ping/pong would alleviate the issue. https://api.slack.com/rtm

**Comment by preludedrew** [comment]
So I looked at the python slackbot, to see how it handled it, and it's very simple. Below is an untested diff is someone would like to test/validate it. If not, I will get some testing done when I can and open a pull request. If you think this would be better added to the scheduler, let me know.

```
diff --git a/machine/core.py b/machine/core.py
index 364c597..14d560d 100644
--- a/machine/core.py
+++ b/machine/core.py
@@ -7,6 +7,8 @@ import dill
 from clint.textui import puts, indent, colored
 import bottle
 
+from six.moves import _thread
+
 from machine.dispatch import EventDispatcher
 from machine.plugins.base import MachineBasePlugin
 from machine.settings import import_settings
@@ -175,6 +177,11 @@ class Machine:
         else:
             return regex.pattern
 
+    def _keepactive(self):
+        while True:
+            time.sleep(30 * 60)
+            self._client.ping()
+
     def run(self):
         announce("\nStarting Slack Machine:")
         with indent(4):
@@ -199,3 +206,5 @@ class Machine:
                 show_valid("Web server started")
             show_valid("Dispatcher started")
             self._dispatcher.start()
+            _thread.start_new_thread(self._keepalive, tuple())
+            show_valid("Keepalive thread started")
```

**Comment by DandyDev** [comment]
I think you added it to the right place. Is there a reason why you use the thread from `six`? Slack Machine doesn't support Python 2.x, so you could just use built-in threading right?

I must add btw, that I'm still not seeing this problem. I've been running a Slack Machine instance for a couple of months now, with little to no activity sometimes, and I never experienced a disconnect.

Maybe we should add the keepalive as a configurable feature, and allow setting a different keepalive as well. So in the configuration: `KEEP_ALIVE = 30 * 60` but with a default of `KEEP_ALIVE = None`. And if `KEEP_ALIVE` is not `None`, start the thread.

**Comment by preludedrew** [comment]
@DandyDev This was almost literally a copy pasta from slackbot, so no there is no particular reason to use thread from six. Let me throw this (and the module change) in and test. If this alleviates the issue, I'll throw a pull request together with this and your suggestion on the setting.

I'm curious why you're unable to replicate. I'm working with a trial of slack (our company is looking to purchas slack), and so far the bot has no activity, besides my testing. Is it possible your bot is getting enough activity to keep it alive? Maybe channel events are enough to keep it alive?

**Comment by DandyDev** [comment]
> Is it possible your bot is getting enough activity to keep it alive?
I've been running Slack Machine at the company I work for, where it gets plenty of activity indeed. But I've also deployed Slack Machine in a Slack team with friends that hardly gets any activity at all, and I'm pretty sure I've told nobody there that I've added a bot.
It might indeed be that listening to channel activity is enough for it.

Anyways, I'm totally willing to merge a PR for this, as long as it's optional/configurable like we talked about :)

BTW, if you can think of any particular features you're missing, either to the core of Slack Machine or in a plugin, let me know about it. I'm always looking to improve SM further

**Comment by DandyDev** [comment]
I'd love some more collaboration on Slack Machine, so any ideas are welcome.

In the meanwhile, I'll have a look at the PR

**Comment by DandyDev** [comment]
@Tahvok I cut a new version with a `KEEP_ALIVE` setting, based on the work of @preludedrew. Can you test if it works for you (if you're still using Slack Machine)? I will leave this issue open for a week or so. If I don't hear anything by then, I'm gonna assume the issue is resolved :)

**Comment by preludedrew** [comment]
Our company finally decided to go with slack, so I'll be working on this a lot more and can validate this issue has been resolved. I'll comment in a week or so and maybe this can get closed. Thanks @DandyDev

**Comment by DandyDev** [comment]
That is awsesome @preludedrew! The procurement department of the company I work for is actually also drawing up contracts with Slack, so hopefully we'll get paid Slack soon, at which time I will be more actively working on slack-machine again.

Any help now and then is much appreciated!

**Comment by preludedrew** [comment]
Been a week and I have yet to see this issue crop up. Makes sense to close to me :)

**Comment by dorel14** [comment]
Hello
I'm facing disconnection problem, i've set up KEEP_ALIVE = 14400
as we can see , we have a client Ping and a client pong  and 5 mns later we see RTM disconnected.

`[2019-08-19 16:38:26][DEBUG] machine.core core.py:_keepalive:185 | Client Ping!
[2019-08-19 16:38:26][DEBUG] machine.dispatch dispatch.py:handle_event:52 | Server Pong!
[2019-08-19 16:43:17][DEBUG] root server.py:websocket_safe_read:290 | RTM disconnected
Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/server.py", line 278, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv
    opcode, data = self.recv_data()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 327, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/core.py", line 219, in run
    self._dispatcher.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/dispatch.py", line 29, in start
    for event in self._client.rtm_read():
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/server.py", line 296, in websocket_safe_read
    "Unable to send due to closed RTM websocket"
slackclient.server.SlackConnectionError: Unable to send due to closed RTM websocket`

**Comment by dorel14** [comment]
hello 
i've set up the KEEP ALIVE parameter and it's always the same
`
[2019-12-10 10:20:05][DEBUG] machine.core core.py:_keepalive:185 | Client Ping!
[2019-12-10 10:20:05][DEBUG] machine.dispatch dispatch.py:handle_event:52 | Server Pong!
127.0.0.1 - - [10/Dec/2019 10:21:58] "GET /meteo HTTP/1.1" 200 0
[2019-12-10 10:25:03][DEBUG] root server.py:websocket_safe_read:290 | RTM disconnected
Traceback (most recent call last):
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/server.py", line 278, in websocket_safe_read
    data += "{0}\n".format(self.websocket.recv())
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 310, in recv
    opcode, data = self.recv_data()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 327, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/home/supportbot/bot/lib/python3.6/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/supportbot/bot/bin/slack-machine", line 10, in <module>
    sys.exit(main())
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/bin/run.py", line 14, in main
    bot.run()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/core.py", line 219, in run
    self._dispatcher.start()
  File "/home/supportbot/bot/lib/python3.6/site-packages/machine/dispatch.py", line 29, in start
    for event in self._client.rtm_read():
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/client.py", line 235, in rtm_read
    json_data = self.server.websocket_safe_read()
  File "/home/supportbot/bot/lib/python3.6/site-packages/slackclient/server.py", line 296, in websocket_safe_read
    "Unable to send due to closed RTM websocket"
slackclient.server.SlackConnectionError: Unable to send due to closed RTM websocket
`
It seems it's merge in new slack-client

**Comment by dorel14** [comment]
Perhaps this issue can be closed , my slack machine is working well in production for 2 weeks as i update to latest version

**Comment by DandyDev** [comment]
Good to hear it's running smoothly for you now!

**Comment by fmb-chin** [comment]
> Perhaps this issue can be closed , my slack machine is working well in production for 2 weeks as i update to latest version

Hello @dorel14 
Could you please tell me which version you use to get rid of this issue? Thank you.

**Comment by dorel14** [comment]
@fmb-chin 
Hello , the latest v0.19.2 is ok for me.
Working now since 2 months without anymore disconnection 
ATke care if you use bottle as i've had in #292

**Comment by fmb-chin** [comment]
@dorel14 Thank you.

I upgraded to v0.19.2 before, but I found message react is broken in v0.19.2 and return to v0.18.2.
I will try v0.19.2 again.

**Comment by dorel14** [comment]
Hi, 
message react os not broken , but sometimes it runs in a timeout , don't know why
